/** Stable asset paths. Swap files under assets/, keep these keys. */

export const brandAssets = {
  homeBanner: '/assets/brand/home-banner.jpg',
  mascots: '/assets/brand/mascots.jpg',
  emptyAlbum: '/assets/brand/empty-album.jpg',
  emptyPlaza: '/assets/brand/empty-plaza.jpg',
  emptyTasks: '/assets/brand/empty-tasks.jpg',
  avatarDefault: '/assets/brand/avatar-default.jpg',
  entryVideo: '/assets/icon/entry-video.jpg',
  entryAlbum: '/assets/icon/entry-album.jpg',
  entryPlaza: '/assets/icon/entry-plaza.jpg',
  entryCheckin: '/assets/icon/entry-checkin.jpg',
  reactLike: '/assets/icon/react-like.png',
  reactLikeOn: '/assets/icon/react-like-active.png',
  reactReply: '/assets/icon/react-reply.png',
  reactReplyOn: '/assets/icon/react-reply-active.png',
  reactFavorite: '/assets/icon/react-favorite.png',
  reactFavoriteOn: '/assets/icon/react-favorite-active.png',
  reactShare: '/assets/icon/react-share.png',
  reactShareOn: '/assets/icon/react-share-active.png',
  gift: '/assets/icon/gift.png',
  composeAlbum: '/assets/icon/compose-album.png',
  composeAlbumOn: '/assets/icon/compose-album-active.png',
  composeEmoji: '/assets/icon/compose-emoji.png',
  composeEmojiOn: '/assets/icon/compose-emoji-active.png',
  composeAt: '/assets/icon/compose-at.png',
  composeAtOn: '/assets/icon/compose-at-active.png',
  composeMic: '/assets/icon/compose-mic.png',
  composeMicOn: '/assets/icon/compose-mic-active.png',
  stickerBlush: '/assets/icon/sticker-blush.jpg',
  stickerHappy: '/assets/icon/sticker-happy.jpg',
  stickerCry: '/assets/icon/sticker-cry.jpg',
  stickerPaw: '/assets/icon/sticker-paw.jpg',
  stickerHeart: '/assets/icon/sticker-heart.jpg',
  stickerSleep: '/assets/icon/sticker-sleep.jpg',
  stickerWow: '/assets/icon/sticker-wow.jpg',
  stickerKiss: '/assets/icon/sticker-kiss.jpg',
} as const

export const mockPhotos = {
  pet1: '/assets/mock/pet-1.jpg',
  pet2: '/assets/mock/pet-2.jpg',
  pet3: '/assets/mock/pet-3.jpg',
} as const
